---
id: language-update-2018-ruby
base_name: language-update-2018-ruby
tags:
- ruby
presentation_date: 2018/08/26
version: 2018.08.26
licenses: []
slideshare_id: language-update-2018-ruby
speaker_deck_id: language-update-2018-ruby
ustream_id:
vimeo_id:
youtube_id:
author:
  markup_language: :markdown
  name: Kazuhiro NISHIYAMA
  email: zn@mbf.nifty.com
  rubygems_user: znz
  slideshare_user: znzjp
  speaker_deck_user: znz
